spring.application.name=url-shortner

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}

# Frontend URL
frontend.url=${FRONTEND_URL}

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:true}

# Cache
spring.cache.type=redis

# Optional Redis cache TTL (1 hour)
spring.cache.redis.time-to-live=3600000

# Optional logging for debugging
logging.level.org.springframework.data.redis=DEBUG